apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nvme-exporter
  labels:
    app: nvme-exporter
spec:
  selector:
    matchLabels:
      app: nvme-exporter
  endpoints:
  - port: metrics
    path: /metrics
