on:
  push:
    branches:
      - main

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: go
          extra-files: |
            - type: yaml
              path: manifests/kustomization.yaml
              jsonpath: "$.images[0].newTag"
